// A big advantage of the Glovo app is its simple interface.
// That means it’s really easy to explain how Glovo works.
// Follow these steps:
//
// You can place Glovo orders to be delivered to your address or enter any other address.
// Hop between bubbles and choose the one that suits your needs best at that moment.
// Buy online through Glovo and confirm your purchase with your card number and delivery details.
//
// The Distro app gives you access to a wide range of delivery services.
// Use the different bubblesto choose the right service for you.
// Make sure you enter your address so you can be shown the services relevant to your area.
// Remember that certain bubbles might be activated or deactivated depending on all kinds of things.
// For example, if we have couriers in your area at the time of your search,
//     you’ll see the Delivery Express service.
// But if there aren’t any around on that day the bubble will remain inactive.

class LangData {
  String name;
  String engName;
  String image;
  bool current;
  int id;

  LangData({required this.name, required this.engName, required this.image, required this.current, required this.id});
}

class Lang {
  static var english = 1;
  static var german = 2;
  static var espanol = 3;
  static var igbo = 4;
  static var yor = 5;
  static var hausa = 6;

  List<LangData> langData = [
    LangData(
        name: "English",
        engName: "English",
        image: "assets/uk.png",
        current: false,
        id: english),
    LangData(
        name: "Germany",
        engName: "Deutsch",
        image: "assets/ger.png",
        current: false,
        id: german),
    LangData(
        name: "Spanish",
        engName: "Spana",
        image: "assets/spain.png",
        current: false,
        id: espanol),
    LangData(
        name: "Igbo",
        engName: "Igbo",
        image: "assets/nig.png",
        current: false,
        id: igbo),
    LangData(
        name: "Yoruba",
        engName: "Yoruba",
        image: "assets/nig.png",
        current: false,
        id: yor),
    LangData(
        name: "Hausa",
        engName: "Hausa",
        image: "assets/nig.png",
        current: false,
        id: hausa),
  ];

  Map<int, String> langDeu = {
    0: "Einführung",
    1: "Distro eröffnet seinen Kunden eine Vielzahl von Optionen, die Lieferungen einfacher und schneller machen.\n\n Die App bietet"
        " Zugriff auf eine Vielzahl von Lieferdiensten wie Fahrräder, Autos, Lastwagen und Flugzeuge. Unsere App ist mehr als nur "
        "Lebensmittellieferungen, bietet aber einen Hauslieferdienst an, der alles liefert, was Sie möglicherweise liefern könnten",
    2: "So verwenden Sie die Distro-App",
    3: "◉ Nachdem Sie sich bei der App angemeldet haben, geben Sie auf dem Startbildschirm Ihre persönlichen Daten ein.\n"
        "\n"
        "◉ Beschreiben Sie auch das zu liefernde Paket und die Menge für einen besseren Lieferservice.\n\n"
        "◉ Wechseln Sie zwischen den Schaltflächen für Transportmittel und wählen Sie diejenige aus, die Ihren Bedürfnissen in diesem Moment am besten entspricht.\n\n"
        "◉ Sie können Distro-Bestellungen aufgeben, die an die gewünschte Adresse geliefert werden. Stellen Sie sicher, dass Sie Ihre korrekte Adresse eingeben, damit Sie leicht gefunden werden können\n\n"
        "◉ Dann können Sie Ihre Zahlung für die Lieferung mit Ihrer Bankkarte abschließen\n\n"
        "◉ Verfolgen Sie Ihre Bestellung in der unteren Leiste und sehen Sie den Fortschritt der Lieferung Ihres Artikels\n\n"
        "◉ Auf dem Startbildschirm befindet sich ein Menüsymbol, über das Sie mit der App interagieren können, um sich damit vertraut zu machen.\n",
    10: "Distribution",
    11: "Überspringen",
    12: "Runter",
    13: "Beginnen wir mit LogIn!",
    14: "Geben Sie Ihre Anmeldedaten ein, um auf Ihr Konto zuzugreifen.",
    15: "Anmelden",
    16: "Passwort",
    17: "Passwort vergessen",
    18: "Weiter",
    19: "Sie haben noch kein Konto? Erstellen",
    20: "Passwort vergessen",
    21: "E-Mail-Adresse",
    22: "ANMELDEN",
    23: "SENDEN",
    24: "Konto erstellen!",
    25: "Passwort bestätigen",
    26: "KONTO ERSTELLEN",
    27: "Um fortzufahren, geben Sie Ihre Telefonnummer ein",
    28: "Telefonnummer",
    29: "WEITER",
    30: "Telefonnummer verifizieren",
    31: "Fast fertig!",
    32: "Codeüberprüfung erfolgreich!!!",
    33: "Zuhause",
    34: "Suchen",
    35: "Benachrichtigungen",
    36: "Sendung verfolgen",
    37: "Konto",
    38: "Nachricht oder Chat",
    39: "Top-Restaurants",
    40: "Diese Woche im Trend",
    41: "Lebensmittelkategorien",
    42: "Am beliebtesten",
    43: "Neueste Bewertungen",
    44: "Keine Benachrichtigungen",
    45: "Benachrichtigungen",
    46: "Das ist eine sehr wichtige Information",
    47: "Karte",
    48: "Adresse",
    49: "Zahlung",
    50: "Geschichte",
    51: "Wie es funktioniert",
    52: "Unbezahlt",
    53: "Versendet",
    54: "Zu versenden",
    55: "Strittig",
    56: "Auftragsliste",
    57: "Benutzername",
    58: "E-Mail",
    59: "Telefon",
    60: "Geschlecht",
    61: "Geburtsdatum",
    62: "Sprachen",
    63: "App-Sprache",
    64: "Produkte",
    65: "Dienste",
    66: "Lieferung",
    67: "Verschiedenes",
    68: "Dienstzeit",
    69: "Informationen",
    70: "Montag",
    71: "Dienstag",
    72: "Mittwoch",
    73: "Donnerstag",
    74: "Freitag",
    75: "Samstag",
    76: "Sonntag",
    77: "Bewertungen",
    78: "Siehe auch",
    79: "Zutaten",
    80: "Ernährung",
    81: "Kalorien",
    82: "Gesamtfett",
    83: "Zucker",
    84: "Kalzium",
    85: "Vitamin D",
    86: "Eiweiß",
    87: "Cholesterin",
    88: "Eisen",
    89: "Extras",
    90: "In den Warenkorb",
    91: "Geschirr",
    92: "Menü",
    93: "Zwischensumme",
    94: "Einkaufskosten",
    95: "Steuern",
    96: "Gesamt",
    97: "Zur Kasse",
    98: "Korb",
    99: "Warenkorb",
    100: "Überprüfen Sie Ihre Menge und klicken Sie auf Zur Kasse",
    101: "Lieferadresse",
    102: "Adresse 1",
    103: "Adresse 2",
    104: "Stadt",
    105: "E-Mail-Adresse",
    106: "Telefon",
    107: "Weiter",
    108: "Kredit-/Debitkarte",
    109: "Nachnahme",
    110: "PayPal",
    111: "Google Wallet",
    112: "Zahlung",
    113: "Methoden",
    114: "Wählen Sie Ihre Zahlungsmethode",
    115: "Bezahlen",
    116: "Erfolg",
    117: "Sie erhalten eine Zahlung an den Verkäufer",
    118: "Fertig",
    119: "Meine Bestellungen",
    120: "Bestellung aufgegeben",
    121: "Zahlung",
    122: "Verarbeitung",
    123: "Unterwegs",
    124: "Lieferung",
    125: "Kommentare",
    126: "Sie erhalten eine Zahlung an den Verkäufer",
    127: "Passwort ändern",
    128: "Profil bearbeiten",
    129: "Altes Passwort",
    130: "Geben Sie Ihr altes Passwort ein",
    131: "Neues Passwort",
    132: "Geben Sie Ihr neues Passwort ein",
    133: "Neues Passwort bestätigen",
    134: "Geben Sie Ihr neues Passwort ein",
    135: "Abbrechen",
    136: "Profil bearbeiten",
    137: "Benutzername",
    138: "Geben Sie Ihren Benutzernamen ein",
    139: "E-Mail",
    140: "Geben Sie Ihre Benutzer-E-Mail ein",
    141: "Geben Sie Ihr Benutzertelefon ein",
    142: "Ändern",
    143: "Galerie öffnen",
    144: "Kamera öffnen",
    145: "Passwort ändern",
    146: "Abholung anfordern",
    147: "Wie lautet Dein voller Name",
    148: "Gib deinen Namen ein",
    149: "Geben Sie Ihre Adresse ein",
    150: "32 George Str, Lekki, Bundesstaat Lagos",
    151: "Geben Sie die Telefonnummer des Absenders ein",
    152: "+234 817 XXX XXXX",
    153: "Rufnummer des Empfängers eingeben",
    154: "Geben Sie die Paketkategorie ein",
    155: "Geben Sie den Paketnamen ein",
    156: "Tücher",
    157: "Produktbeschreibung eingeben",
    158: "Rosa Materialien mit Steindesigns",
    159: "Wählen Sie Abholadresse aus",
    160: "Produktbeschreibung",
    161: "Wählen Sie Lieferadresse aus",
    162: "Anfrage",
    163: "Abholung anfordern",
    164: "Schnell",
    165: "Zuverlässig",
    166: "Effizient",
    167:
        "Schneller innerstädtischer Kurierdienst. Einfache Logistik für Unternehmen.",
    168: "Zuverlässige Zustellung fürs Geschäft",
    169: "Effizienter und sicherer Prozess",
    170: "Willkommen in unserer Welt",
    171: "Sie können jetzt damit beginnen, Abholbestellungen aufzugeben",
    172: "Ihre Bestellung wird bearbeitet",
    173: "Ihr Abholauftrag ist eingegangen und wird bearbeitet",
    174: "Artikel Menge"
  };

  Map<int, String> langEsp = {
    0: "Introducción",
    1: "Distro abre una variedad de opciones a sus clientes haciendo que las entregas sean más fáciles y rápidas.\n\n La aplicación ofrece"
        " acceda a una variedad de servicios de entrega como bicicletas, automóviles, camiones y aviones. Nuestra aplicación es más que solo "
        "entregas de alimentos pero ofrece servicio de entrega a domicilio entregando cualquier cosa que pueda entregar",
    2: "Cómo usar la aplicación de distribución",
    3: "◉ Después de iniciar sesión en la aplicación, en la pantalla de inicio, complete sus datos personales.\n"
        "\norte"
        "◉ Describa también el paquete a entregar y el monto para un mejor servicio de entrega.\n\n"
        "◉ Salta entre los botones de medios de transporte y elige el que mejor se adapte a tus necesidades en ese momento.\n\n"
        "◉ Puede realizar pedidos de distribución para que se entreguen en la dirección solicitada. Asegúrese de ingresar su dirección correcta para que pueda ser descubierto fácilmente\n\n"
        "◉ Luego, utilizando su tarjeta bancaria, puede finalizar el pago de la entrega\n\n"
        "◉ Realice un seguimiento de su pedido desde la barra inferior y vea el progreso de cómo se entrega su artículo\n\n"
        "◉ Hay un ícono de menú en la pantalla de inicio donde puedes interactuar con la aplicación para familiarizarte con ella.\n",
    10: "Distribución",
    11: "Saltar",
    12: "Abajo",
    13: "¡Comencemos con Iniciar sesión!",
    14: "Ingrese sus datos de inicio de sesión para acceder a su cuenta.",
    15: "Iniciar sesión",
    16: "Contraseña",
    17: "Olvidé mi contraseña",
    18: "Continuar",
    19: "¿No tienes una cuenta? Crear",
    20: "Olvidé mi contraseña",
    21: "Dirección de correo electrónico",
    22: "INICIAR SESIÓN",
    23: "ENVIAR",
    24: "¡Crea una cuenta!",
    25: "Confirmar contraseña",
    26: "CREAR CUENTA",
    27: "Para continuar introduce tu número de teléfono",
    28: "Número de teléfono",
    29: "CONTINUAR",
    30: "Verificar número de teléfono",
    31: "¡Casi listo!",
    32: "¡¡Verificación de código exitosa!!!",
    33: "Casa",
    34: "Buscar",
    35: "Notificaciones",
    36: "Rastrear envío",
    37: "Cuenta",
    38: "Mensaje o chat",
    39: "Los Mejores Restaurantes",
    40: "Tendencia esta semana",
    41: "Categorías de alimentos",
    42: "Más popular",
    43: "Comentarios recientes",
    44: "No tengo notificaciones",
    45: "Notificaciones",
    46: "Esta es una información muy importante",
    47: "Mapa",
    48: "Dirección",
    49: "Pago",
    50: "Historia",
    51: "Cómo funciona",
    52: "Sin pagar",
    53: "Enviado",
    54: "Para ser enviado",
    55: "En disputa",
    56: "Lista de pedidos",
    57: "Nombre de usuario",
    58: "Correo electrónico",
    59: "Teléfono",
    60: "Género",
    61: "Fecha de nacimiento",
    62: "Idiomas",
    63: "Idioma de la aplicación",
    64: "Productos",
    65: "Servicios",
    66: "Entrega",
    67: "Varios",
    68: "Término de servicio",
    69: "Información",
    70: "lunes",
    71: "martes",
    72: "miércoles",
    73: "jueves",
    74: "Viernes",
    75: "Sábado",
    76: "Domingo",
    77: "Reseñas",
    78: "Véase también",
    79: "Ingredientes",
    80: "Nutrición",
    81: "Calorías",
    82: "Grasa total",
    83: "Azúcares",
    84: "Calcio",
    85: "Vitamina D",
    86: "Proteína",
    87: "colesterol",
    88: "Hierro",
    89: "Extras",
    90: "Añadir al carrito",
    91: "Platos",
    92: "Menú",
    93: "Subtotal",
    94: "Costos de compras",
    95: "Impuestos",
    96: "Total",
    97: "Pagar",
    98: "Cesta",
    99: "Carrito de la compra",
    100: "Verifique su cantidad y haga clic en pagar",
    101: "Dirección de entrega",
    102: "Dirección 1",
    103: "Dirección 2",
    104: "Ciudad",
    105: "Dirección de correo electrónico",
    106: "Teléfono",
    107: "Siguiente",
    108: "Tarjeta de crédito/débito",
    109: "Contrareembolso",
    110: "PayPal",
    111: "Google Monedero",
    112: "Pago",
    113: "Métodos",
    114: "Elige tu método de pago",
    115: "Pagar",
    116: "Éxito",
    117: "Usted recibe el pago del vendedor",
    118: "Hecho",
    119: "Mis pedidos",
    120: "Pedido realizado",
    121: "Pago",
    122: "Procesamiento",
    123: "En camino",
    124: "Entrega",
    125: "Comentarios",
    126: "Usted recibe el pago del vendedor",
    127: "Cambiar contraseña",
    128: "Editar perfil",
    129: "Contraseña antigua",
    130: "Ingrese su antigua contraseña",
    131: "Nueva contraseña",
    132: "Ingrese su nueva contraseña",
    133: "Confirmar nueva contraseña",
    134: "Ingrese su nueva contraseña",
    135: "Cancelar",
    136: "Editar perfil",
    137: "Nombre de usuario",
    138: "Ingrese su Nombre de Usuario",
    139: "Correo electrónico",
    140: "Ingrese su correo electrónico de usuario",
    141: "Ingresa tu Teléfono de Usuario",
    142: "Cambiar",
    143: "Galería abierta",
    144: "Cámara abierta",
    145: "Cambiar contraseña",
    146: "Solicitar una recogida",
    147: "Cuál es su nombre completo",
    148: "Introduzca su nombre",
    149: "Ingrese su dirección",
    150: "Calle George 32, Lekki, Estado de Lagos",
    151: "Ingrese el número de teléfono del remitente",
    152: "+234 817 XXX XXXX",
    153: "Ingrese el número de teléfono del receptor",
    154: "Ingrese a la categoría del paquete",
    155: "Ingrese el nombre del paquete",
    156: "Telas",
    157: "Ingrese la descripción del producto",
    158: "Materiales rosas con diseños de piedra",
    159: "Seleccione la dirección de recogida",
    160: "Descripción del producto",
    161: "Seleccionar dirección de entrega",
    162: "Solicitud",
    163: "Solicitar una recogida",
    164: "Rápido",
    165: "Confiable",
    166: "Eficiente",
    167:
        "Servicio rápido de entrega de mensajería dentro de la ciudad. Fácil logística para los negocios.",
    168: "Entrega confiable para negocios",
    169: "Proceso eficiente y seguro",
    170: "Bienvenidos a nuestro mundo",
    171: "Puedes empezar a hacer pedidos para recoger ahora mismo",
    172: "Su pedido está siendo procesado",
    173: "Su orden de recogida ha sido recibida y está siendo procesada",
    174: "Cantidad de objetos"
  };

  Map<int, String> langEng = {
    0: "Introduction",
    1: " Distro opens a variety of options to its customers making deliveries easier and faster.\n\n The app gives"
        " access to a variety of delivery services such as bikes, cars, trucks and planes. Our app is more than just "
        "food deliveries but offers home delivery service delivering anything you could possibly deliver",
    2: "How to use the Distro App",
    3: "◉ After you login into the app, on the home screen, fill in your personal details.\n"
        "\n"
        "◉ Describe also the package to be delivered and amount for better delivery service.\n\n"
        "◉ Hop between transport means buttons and choose the one that suits your needs best at that moment.\n\n"
        "◉ You can place Distro orders to be delivered to the requested address. Make sure you enter your correct address so you can be easily discovered\n\n"
        "◉ Then using your bank card, you can finalize your payment for the delivery\n\n"
        "◉ Track your order from the bottom bar and see the progress of how your item is delivered\n\n"
        "◉ There's a menu icon on the home screen where you can interact with the app get familiar with it.\n",
    10: "Distro",
    11: "Skip",
    12: "Down",
    13: "Let's start with logging you in!",
    14: "Enter you login details to access your account.",
    15: "Login",
    16: "Password",
    17: "Forgot password",
    18: "Continue",
    19: "Don't have an account? Create",
    20: "Forgot password",
    21: "E-mail address",
    22: "LOGIN",
    23: "SEND",
    24: "Create an Account!",
    25: "Confirm Password",
    26: "CREATE ACCOUNT",
    27: "To continue enter your phone number",
    28: "Phone number",
    29: "CONTINUE",
    30: "Verify phone number",
    31: "Almost done!",
    32: "Code verification success!!!",
    33: "Home",
    34: "Search",
    35: "Notifications",
    36: "Track Shipment",
    37: "Account",
    38: "Message or chat",
    39: "Top Restaurants",
    40: "Trending this week",
    41: "Food categories",
    42: "Most Popular",
    43: "Recent Reviews",
    44: "No Notifications",
    45: "Notifications",
    46: "This is a very important information",
    47: "Map",
    48: "Address",
    49: "Payment",
    50: "History",
    51: "How it works",
    52: "Unpaid",
    53: "Shipped",
    54: "To be Shipped",
    55: "In Dispute",
    56: "Orders List",
    57: "Username",
    58: "E-mail",
    59: "Phone",
    60: "Gender",
    61: "Date of birth",
    62: "Languages",
    63: "App Language",
    64: "Products",
    65: "Services",
    66: "Delivery",
    67: "Misc",
    68: "Term of service",
    69: "Information",
    70: "Monday",
    71: "Tuesday",
    72: "Wednesday",
    73: "Thursday",
    74: "Friday",
    75: "Saturday",
    76: "Sunday",
    77: "Reviews",
    78: "See Also",
    79: "Ingredients",
    80: "Nutrition",
    81: "Calories",
    82: "Total Fat",
    83: "Sugars",
    84: "Calcium",
    85: "Vitamin D",
    86: "Protein",
    87: "Cholesterol",
    88: "Iron",
    89: "Extras",
    90: "Add to cart",
    91: "Dishes",
    92: "Menu",
    93: "Subtotal",
    94: "Shopping costs",
    95: "Taxes",
    96: "Total",
    97: "Checkout",
    98: "Basket",
    99: "Shopping Cart",
    100: "Verify your quantity and click checkout",
    101: "Delivery Address",
    102: "Address 1",
    103: "Address 2",
    104: "City",
    105: "Email address",
    106: "Phone",
    107: "Next",
    108: "Credit/Debit Card",
    109: "Cash On Delivery",
    110: "PayPal",
    111: "Google Wallet",
    112: "Payment",
    113: "Methods",
    114: "Choose your payment method",
    115: "Pay",
    116: "Success",
    117: "Your Payment has been received",
    118: "Done",
    119: "My Orders",
    120: "Order placed",
    121: "Payment ",
    122: "Processing",
    123: "On the way",
    124: "Delivery",
    125: "Comments",
    126: "Your Payment method has been received",
    127: "Change password",
    128: "Edit profile",
    129: "Old password",
    130: "Enter your old password",
    131: "New password",
    132: "Enter your new password",
    133: "Confirm New password",
    134: "Enter your new password",
    135: "Cancel",
    136: "Edit profile",
    137: "User Name",
    138: "Enter your User Name",
    139: "E-mail",
    140: "Enter your User E-mail",
    141: "Enter your User Phone",
    142: "Change",
    143: "Open Gallery",
    144: "Open Camera",
    145: "Change password",
    146: "Request a Pickup",
    147: "Full Name",
    148: "Enter your name",
    149: "Enter your Address",
    150: "32 George Str, Lekki, Lagos State",
    151: "Enter Sender's Phone No",
    152: "+234 *** *** ****",
    153: "Phone number",
    154: "Select Package Type",
    155: "Enter the Package Name",
    156: "Cloths",
    157: "Enter Product Description",
    158: "Pink Materials with stone designs",
    159: "Select Pick-up Address",
    160: "Package Description",
    161: "Select Delivery Address",
    162: "Request",
    163: "Request A Pickup",
    164: "Fast",
    165: "Reliable",
    166: "Efficient",
    167:
        "Fast intracity courier delivery service. Easy logistics for business.",
    168: "Reliable delivery for business",
    169: "Efficient and secure process",
    170: "Welcome",
    171: "You can begin making pickup orders right now",
    172: "Your Order is being processed",
    173: "Your pickup order has been received and is being processed",
    174: "Quantity"
  };

  Map<int, String> langIgbo = {
    0: "Mmalite",
    1: " Distro na-emepere ndị ahịa ya nhọrọ dị iche iche na-eme ka nnyefe dị mfe yana ngwa ngwa.\n\n Ngwa ahụ na-enye"
        "ịnweta ọrụ nnyefe dị iche iche dị ka igwe kwụ otu ebe, ụgbọ ala, gwongworo na ụgbọ elu. Ngwa anyị karịrị naanị "
        "Nwepụta nri mana na-enye ọrụ nnyefe ụlọ na-ebuga ihe ọ bụla ị nwere ike ibunye",
    2: "Otu esi eji ngwa Distro",
    3:"◉ Mgbe ibanye na ngwa a, n'ihuenyo ụlọ, dejupụta nkọwa nkeonwe gị.\n"
        "\n"
        "◉ Kọwaa kwa ngwugwu a ga-ebunye yana ego maka ọrụ nnyefe ka mma.\n\n"
        "◉ Ntụgharị n'etiti njem pụtara bọtịnụ wee họrọ nke dabara gị mma n'oge ahụ.\n\n"
        "◉ Ị nwere ike ịnye iwu Distro ka ebuga ya na adreesị achọrọ. Gbaa mbọ hụ na itinye adreesị gị ziri ezi ka enwere ike ịchọta gị ngwa ngwa\n\n"
        "◉ Mgbe ahụ na-eji kaadị akụ gị, ị nwere ike mechaa ịkwụ ụgwọ gị maka nnyefe\n\n"
        "◉ Soro usoro gị si n'okpuru mmanya wee hụ ọganihu otu esi ebufe ihe gị\n\n"
        "◉ Enwere akara ngosi menu na ihuenyo ụlọ ebe ị nwere ike imekọrịta ngwa na nke ọma.\n",
    10: "Distro",
    11: "Mafee",
    12: "Ala",
    13: "Ka anyị malite na Nbanye!",
    14: "Tinye nkọwa nbanye gị iji nweta akaụntụ gị.",
    15: "Banye",
    16: "Okwuntughe",
    17: "Chefuru okwuntughe",
    18: "Gaa n'ihu",
    19: "Ịnweghị akaụntụ? Mepụta",
    20: "Chefuru okwuntughe",
    21: "Adreesị ozi ịntanetị",
    22: "BANYE",
    23: "ZIPU",
    24: "Mepụta akaụntụ!",
    25: "Kwenye Na Okwuntughe",
    26: "MEBE AKAỤNTỤ",
    27: "Ka ịga n'ihu tinye akara ekwentị gị",
    28: "Nọmba ekwentị",
    29: "Gaa n'ihu",
    30: "Nyochaa nọmba ekwentị",
    31: "Ọ fọrọ nke nta ka emechaa!",
    32: "Ọganihu nkwenye koodu!!!",
    33: "Ụlọ",
    34: "Chọọ",
    35: "Amamọkwa",
    36: "Mbupu soro",
    37: "Akaụntụ",
    38: "Ozi ma ọ bụ nkata",
    39: "Ụlọ oriri na ọṅụṅụ kacha mma",
    40: "Trending n'izu a",
    41: "Ụdị nri",
    42: "Kacha ewu ewu",
    43: "Nlebanya nso nso a",
    44: "Enweghị ọkwa",
    45: "Amamọkwa",
    46: "Nke a bụ ozi dị ezigbo mkpa",
    47: "Maapụ",
    48: "Adreesị",
    49: "Ịkwụ ụgwọ",
    50: "Akụkọ ihe mere eme",
    51: "Ka o si arụ ọrụ",
    52: "Akwụghị ụgwọ",
    53: "Ebufere",
    54: "A ga-ebupu ya",
    55: "Na esemokwu",
    56: "Ndepụta iwu",
    57: "Aha njirimara",
    58: "E-mail",
    59: "Nọmba ekwentị",
    60: "okike",
    61: "Ụbọchị ọmụmụ",
    62: "Asụsụ",
    63: "App Language",
    64: "Ngwaahịa",
    65: "Ọrụ",
    66: "Nnyefe",
    67: "Misc",
    68: "Oge ọrụ",
    69: "Ozi",
    70: "Monday",
    71: "Tuzdee",
    72: "Ụbọchị Wenezdee",
    73: "Thursday",
    74: "Friday",
    75: "Saturday",
    76: "Ụbọchị Sọnde",
    77: "Nlebanya",
    78: "Leekwa",
    79: "Egwere",
    80: "Nri nri",
    81: "Kalori",
    82: "Mkpokọta abụba",
    83: "Sugar",
    84: "Calcium",
    85: "Vitamin D",
    86: "Protein",
    87: "Cholesterol",
    88: "ígwè",
    89: "Mgbakwunye",
    90: "Tinye na ụgbọ ibu",
    91: "Efere",
    92: "NchNhr",
    93: "Mkpokọta",
    94: "Ọnụ ahịa ịzụ ahịa",
    95: "Ụtụ isi",
    96: "Ngụkọta",
    97: "Chekwaa",
    98: "Nkata",
    99: "ụgbọ ịzụ ahịa",
    100: " Nyochaa ọnụọgụ gị wee pịa ndenye ego",
    101: "Adreesi nnyefe",
    102: "Adreesị 1",
    103: "Adreesị 2",
    104: "Obodo",
    105: "Adreesi email",
    106: "ekwentị",
    107: "Ọzọ",
    108: "Kaadị kredit/Debit",
    109: "Ego Na Nnyefe",
    110: "PayPal",
    111: "Google Wallet",
    112: "Ụgwọ",
    113: "Ụzọ",
    114: "Họrọ usoro ịkwụ ụgwọ gị",
    115: "Kwụọ",
    116: "Ihe ịga nke ọma",
    117: "Ị na-anata onye na-ere ere",
    118: "Emela",
    119: "Iwu m",
    120: "Edobere iwu",
    121: "Ụgwọ",
    122: "Nhazi",
    123: "N'ụzọ",
    124: "Nnyefe",
    125: "Nkwupụta",
    126: "Ị na-anata onye na-ere ere",
    127: "Gbanwee paswọọdụ",
    128: "Dezie profaịlụ",
    129: "Password ochie",
    130: "Tinye paswọọdụ ochie gị",
    131: "Password ọhụrụ",
    132: "Tinye paswọọdụ ọhụrụ gị",
    133: "Kwenye paswọọdụ ọhụrụ",
    134: "Tinye paswọọdụ ọhụrụ gị",
    135: "Kagbuo",
    136: "Dezie profaịlụ",
    137: "Aha njirimara",
    138: "Tinye aha njirimara gị",
    139: "E-mail",
    140: "Tinye ozi-e onye ọrụ gị",
    141: "Tinye ekwentị onye ọrụ gị",
    142: "Mgbanwe",
    143: "Ụlọ ihe ngosi mepere emepe",
    144: "igwefoto mepere emepe",
    145: "Gbanwee paswọọdụ",
    146: "Rịọ ntụtụ",
    147: "Kedu aha gị n'uju",
    148: "Tinye aha gị",
    149: "Tinye adreesị gị",
    150: "32 George Str, Lekki, Lagos State",
    151: "Tinye ekwentị nke onye zitere",
    152: "+234 817 XXX XXXX",
    153: "Tinye ekwentị onye nnata Mba",
    154: "Tinye Ụdị ngwugwu",
    155: "Tinye Aha ngwugwu",
    156: "Akwa",
    157: "Tinye nkọwa ngwaahịa",
    158: "Ihe eji eme ihe na-acha odo odo nwere atụmatụ nkume",
    159: "Họrọ Adreesị mbubata",
    160: "Nkọwa ngwaahịa",
    161: "Họrọ adreesị nnyefe",
    162: "Arịrịọ",
    163: "Rịọ ntụtụ",
    164: "Ọsọ ọsọ",
    165: "Enwere ntụkwasị obi",
    166: "Oma",
    167: "Ọrụ nnyefe ozi intracity ngwa ngwa. Ngwa ngwa dị mfe maka azụmahịa.",
    168: "Nfefe ntụkwasị obi maka azụmahịa",
    169: "Usoro dị mma na nchekwa",
    170: "Nnọọ n'ụwa anyị",
    171: "Ị nwere ike ịmalite ịme iwu mbubata ugbu a",
    172: "A na-ahazi iwu gị",
    173: "Anatala akwụkwọ mbupu gị ma na-ahazi ya",
    174: "Ọnụọgụ ihe"
  };

  Map<int, String> langYor = {
    0: "Ifihan",
    1: " Distro ṣi oniruuru awọn aṣayan si awọn onibara rẹ ti nmu awọn ifijiṣẹ rọrun ati yiyara.\n\n Ohun elo naa n funni"
        "Wiwọle si ọpọlọpọ awọn iṣẹ ifijiṣẹ gẹgẹbi awọn keke, awọn ọkọ ayọkẹlẹ, awọn oko nla ati awọn ọkọ ofurufu. Ohun elo wa ju o kan lọ "
        "Awọn ifijiṣẹ ounje ṣugbọn o funni ni iṣẹ ifijiṣẹ ile ti n pese ohunkohun ti o le ṣe jiṣẹ",
    2: "Bi o ṣe le lo Ohun elo Distro",
    3:"◉ Lẹ́yìn tí ẹ bá ti wọlé sínú ìṣàfilọ́lẹ̀ náà, lójú ìṣàmúlò ilé, ẹ kún àwọn kúlẹ̀kúlẹ̀ àdáni rẹ.\n"
        "\n"
        "◉ Ṣapejuwe tun package ti o yẹ ki o fi jiṣẹ ati iye fun iṣẹ ifijiṣẹ to dara julọ.\n\n"
        "◉ Hop laarin gbigbe tumo si awọn bọtini ati ki o yan eyi ti o baamu awọn iwulo rẹ dara julọ ni akoko yẹn.\n\n"
        "◉ O le fi awọn aṣẹ Distro silẹ lati fi jiṣẹ si adirẹsi ti o beere. Rii daju pe o tẹ adirẹsi sii ti o pe ki o le ṣawari ni irọrun\n\n"
        "◉ Lẹhinna lilo kaadi banki rẹ, o le pari isanwo rẹ fun ifijiṣẹ\n\n"
        "◉ Tọpinpin aṣẹ rẹ lati ọpa isale ki o wo ilọsiwaju ti bi a ṣe fi nkan rẹ jiṣẹ\n\n"
        "◉ Aami akojọ aṣayan kan wa loju iboju ile nibi ti o ti le ṣe ibaṣepọ pẹlu ohun elo naa faramọ pẹlu rẹ.\n",
    10: "Distro",
    11: "Rekọja",
    12: "Isalẹ",
    13: "Jẹ ki a bẹrẹ pẹlu LogIn!",
    14: "Tẹ awọn alaye iwọle sii lati wọle si akọọlẹ rẹ.",
    15: "Wọle",
    16: "Ọrọigbaniwọle",
    17: "Gbagbe ọrọ igbaniwọle",
    18: "Tẹsiwaju",
    19: "Ṣe ko ni akọọlẹ kan? Ṣẹda",
    20: "Gbagbe ọrọ igbaniwọle",
    21: "Adirẹsi imeeli",
    22: "Wiwọle",
    23: "Firanṣẹ",
    24: "Ṣẹda akọọlẹ kan!",
    25: "Jẹrisi ọrọ igbaniwọle",
    26: "ṢẸDA AKỌKỌ",
    27: "Lati tẹsiwaju tẹ nọmba foonu rẹ sii",
    28: "Nọmba foonu",
    29: "Tẹsiwaju",
    30: "Ṣe daju nọmba foonu",
    31: "O fẹrẹ ṣe!",
    32: "Aṣeyọri ijẹrisi koodu !!!",
    33: "Ile",
    34: "Ṣawari",
    35: "Awọn iwifunni",
    36: "Ipa-Ipa-irin",
    37: "Account",
    38: "Ifiranṣẹ tabi iwiregbe",
    39: "Awọn ounjẹ ti o ga julọ",
    40: "Ti n ṣe ni ọsẹ yii",
    41: "Awọn ẹka onjẹ",
    42: "Gbigbajugbajulọ",
    43: "Awọn atunyẹwo aipẹ",
    44: "Ko ni Awọn iwifunni",
    45: "Awọn iwifunni",
    46: "Eyi jẹ alaye pataki pupọ",
    47: "Map",
    48: "Adirẹsi",
    49: "Isanwo",
    50: "Itan",
    51: "Bawo ni o ṣe n ṣiṣẹ",
    52: "A ko sanwo",
    53: "Ti a fi ranse",
    54: "Lati firanṣẹ",
    55: "Ninu Ijiyan",
    56: "Akojọ awọn aṣẹ",
    57: "Orukọ olumulo",
    58: "E-mail",
    59: "Foonu",
    60: "Ibi",
    61: "Ọjọ ibi",
    62: "Awọn ede",
    63: "Ede App",
    64: "Awọn ọja",
    65: "Awọn iṣẹ",
    66: "Ifijiṣẹ",
    67: "Orisi",
    68: "Àkókò iṣẹ́",
    69: "Alaye",
    70: "Ojo Aje",
    71: "Ojo Isegun",
    72: "Ojoru",
    73: "Ọjọbọ",
    74: "Eti",
    75: "Abameta",
    76: "Aiku",
    77: "Awọn atunyẹwo",
    78: "Wo Bakannaa",
    79: "Awọn eroja",
    80: "Ounjẹ",
    81: "Awọn kalori",
    82: "Apapọ Ọra",
    83: "Suga",
    84: "Calcium",
    85: "Vitamin D",
    86: "Amuaradagba",
    87: "Cholesterol",
    88: "Irin",
    89: "Awọn afikun",
    90: "Fi kun si kẹkẹ",
    91: "Awọn awopọ",
    92: "Akojọ aṣyn",
    93: "Apapọ",
    94: "Awọn idiyele rira",
    95: "Awọn owo-ori",
    96: "Lapapọ",
    97: "Iyẹwo",
    98: "Agbọn",
    99: "Ọkọ rira",
    100: "Ṣe daju iye rẹ ki o tẹ ibi isanwo",
    101: "Adirẹsi Ifijiṣẹ",
    102: "Adirẹsi 1",
    103: "Adirẹsi 2",
    104: "Ilu",
    105: "Adirẹsi imeeli",
    106: "Foonu",
    107: "Itele",
    108: "Kirẹditi/Kaadi Debiti",
    109: "Owo Lori Ifijiṣẹ",
    110: "PayPal",
    111: "Google apamọwọ",
    112: "Isanwo",
    113: "Awọn ọna",
    114: "Yan ọna isanwo rẹ",
    115: "Sanwo",
    116: "Aseyori",
    117: "Iwọ Gba Owo sisan fun Olutaja",
    118: "Ti ṣee",
    119: "Awọn aṣẹ Mi",
    120: "Ibere ti a fi",
    121: "Isanwo",
    122: "Ṣiṣe ilana",
    123: "Ni ọna",
    124: "Ifijiṣẹ",
    125: "Awọn asọye",
    126: "Iwọ Gba Owo sisan fun Olutaja",
    127: "Yi ọrọ igbaniwọle pada",
    128: "Ṣatunkọ profaili",
    129: "Ọrọigbaniwọle atijọ",
    130: "Tẹ ọrọ igbaniwọle atijọ rẹ sii",
    131: "Ọrọigbaniwọle titun",
    132: "Tẹ ọrọ igbaniwọle titun rẹ sii",
    133: "Jẹrisi ọrọ igbaniwọle Tuntun",
    134: "Tẹ ọrọ igbaniwọle titun rẹ sii",
    135: "Fagilee",
    136: "Ṣatunkọ profaili",
    137: "Orukọ olumulo",
    138: "Tẹ Orukọ olumulo rẹ sii",
    139: "E-mail",
    140: "Tẹ imeeli olumulo rẹ",
    141: "Tẹ foonu olumulo rẹ sii",
    142: "Yipada",
    143: "Ile-iṣẹ Ṣiṣii",
    144: "Kamẹra Ṣii",
    145: "Yi ọrọ igbaniwọle pada",
    146: "Beere fun Gbigba",
    147: "Kini oruko re ni kikun",
    148: "Tẹ orukọ rẹ sii",
    149: "Tẹ adirẹsi rẹ sii",
    150: "32 George Str, Lekki, Lagos State",
    151: "Tẹ Foonu Olufiranṣẹ Ko si",
    152: "+234 817 XXX XXXX",
    153: "Tẹ Foonu Olugba wọle Bẹẹkọ",
    154: "Tẹ Ẹka Package sii",
    155: "Tẹ Orukọ Package sii",
    156: "Aṣọ",
    157: "Tẹ Apejuwe Ọja",
    158: "Awọn ohun elo Pink pẹlu awọn apẹrẹ okuta",
    159: "Yan Adirẹsi Gbe",
    160: "Apejuwe ọja",
    161: "Yan Adirẹsi Ifijiṣẹ",
    162: "Ibere",
    163: "Bere fun Gbigba",
    164: "Yara",
    165: "Gbẹkẹle",
    166: "Dáfáfá",
    167: "Yara intracity Oluranse ifijiṣẹ iṣẹ. Awọn eekaderi irọrun fun iṣowo.",
    168: "Ifijiṣẹ ti o gbẹkẹle fun iṣowo",
    169: "Ilana daradara ati aabo",
    170: "Kaabo si aye wa",
    171: "O le bẹrẹ ṣiṣe awọn ibere gbigba ni bayi",
    172: "Iṣẹ rẹ ti n ṣiṣẹ",
    173: "Ibere ​​gbigba rẹ ti gba ati pe o ti ni ilọsiwaju",
    174: "Opoiye nkan elo"
  };

  Map<int, String> langHausa = {
    0: "Gabatarwa",
    1: " Distro yana buɗe zaɓuɓɓuka iri-iri ga abokan cinikin sa suna yin sauƙi da sauri.\n\n App ɗin yana bayarwa"
        " samun dama ga sabis na isar da kayayyaki iri-iri kamar kekuna, motoci, manyan motoci da jiragen sama. App ɗinmu ya wuce kawai"
        "Kayan abinci amma yana ba da sabis na isar da gida yana isar da duk abin da za ku iya bayarwa",
    2: "Yadda ake amfani da Distro App",
    3: "◉ Bayan ka shiga app, akan allon gida, cika bayanan sirrinka.\n"
        "\n"
        "◉ Yi bayanin fakitin da za a isar da adadin don ingantaccen sabis na isarwa.\n\n"
        "◉ Yi tsalle tsakanin sufuri yana nufin maɓalli kuma zaɓi wanda ya fi dacewa da buƙatunku a lokacin.\n\n"
        "◉ Kuna iya ba da odar Distro don isar da shi zuwa adireshin da ake buƙata. Tabbatar kun shigar da daidai adireshin ku don a iya gano ku cikin sauƙi\n\n"
        "◉ Sannan ta amfani da katin banki, zaku iya kammala biyan kuɗin ku don isarwa\n\n"
        "◉ Bibiyar odar ku daga sandar ƙasa kuma duba ci gaban yadda ake isar da kayanku\n\n"
        "◉ Akwai gunkin menu akan allon gida inda zaku iya hulɗa da app ɗin ku saba dashi.\n",
    10: "Distro",
    11: "Tsalle",
    12: "Ƙasa",
    13: "Bari mu fara da LogIn!",
    14: "Shigar da bayanan shiga don samun damar asusunku.",
    15: "Shigo",
    16: "Password",
    17: "An manta kalmar sirri",
    18: "Ci gaba",
    19: "Ba ku da asusu? Ƙirƙiri",
    20: "An manta kalmar sirri",
    21: "Adreshin Imel",
    22: "Shiga",
    23: "Aika",
    24: "Ƙirƙiri Account!",
    25: "Tabbatar da kalmar wucewa",
    26: "KI KIRKIRA ASUSU",
    27: "Don ci gaba da shigar da lambar wayar ku",
    28: "Lambar waya",
    29: "CIGABA",
    30: "Tabbatar lambar waya",
    31: "Kusan an gama!",
    32: "Nasarar tabbatar da lambar!!!",
    33: "Gida",
    34: "Bincika",
    35: "Sanarwa",
    36: "Tsarin Jirgin Ruwa",
    37: "Asusu",
    38: "Sako ko hira",
    39: "Manyan gidajen cin abinci",
    40: "Trending a wannan makon",
    41: "Kayan abinci",
    42: "Mafi Shahara",
    43: "Bita na Kwanan nan",
    44: "Babu Sanarwa",
    45: "Sanarwa",
    46: "Wannan muhimmin bayani ne",
    47: "Taswira",
    48: "Adireshi",
    49: "Biyan kuɗi",
    50: "Tarihi",
    51: "Yadda yake aiki",
    52: "Ba a biya ba",
    53: "An aika",
    54: "Za a yi jigilar kaya",
    55: "A cikin Rigima",
    56: "Jerin umarni",
    57: "Sunan mai amfani",
    58: "E-mail",
    59: "waya",
    60: "jinsi",
    61: "Ranar haihuwa",
    62: "harsuna",
    63: "App Language",
    64: "Kayayyakin",
    65: "Sabis",
    66: "Bayarwa",
    67: "Misc",
    68: "Lokacin sabis",
    69: "Bayanai",
    70: "Litinin",
    71: "Talata",
    72: "Laraba",
    73: "Alhamis",
    74: "Jumma'a",
    75: "Asabar",
    76: "Lahadi",
    77: "Bita",
    78: "Dubi kuma",
    79: "Kayan Sinadari",
    80: "Abincin Abinci",
    81: "Kalori",
    82: "Jimlar Fat",
    83: "Sukari",
    84: "Calcium",
    85: "Vitamin D",
    86: "Protein",
    87: "Cholesterol",
    88: "Iron",
    89: "Ƙari",
    90: "Ƙara zuwa cart",
    91: "Ajiye",
    92: "Menu",
    93: "Ƙarfafawa",
    94: "Kudin siyayya",
    95: "Haraji",
    96: "Jimlar",
    97: "Bari",
    98: "Kwando",
    99: "Katin Siyayya",
    100: "Tabbatar da adadin ku kuma danna wurin biya",
    101: "Adireshin Bayarwa",
    102: "Adireshi 1",
    103: "Adireshi 2",
    104: "Birni",
    105: "Adreshin Imel",
    106: "Waya",
    107: "Na gaba",
    108: "Katin Credit/Credit",
    109: "Kudi Kan Bayarwa",
    110: "PayPal",
    111: "Google Wallet",
    112: "Biyan kuɗi",
    113: "Hanyoyi",
    114: "Zaɓi hanyar biyan ku",
    115: "Biya",
    116: "Nasara",
    117: "Ku Biyan Kuɗi Ga Mai siyarwa",
    118: "An gama",
    119: "Umurna Na",
    120: "An yi oda",
    121: "Biyan kuɗi",
    122: "Tsarin aiki",
    123: "A kan hanya",
    124: "Bayarwa",
    125: "Magana",
    126: "Ku Biyan Kuɗi ga Mai siyarwa",
    127: "Canja kalmar sirri",
    128: "Shirya bayanin martaba",
    129: "Tsohon kalmar sirri",
    130: "Shigar da tsohon kalmar sirri",
    131: "Sabon kalmar sirri",
    132: "Shigar da sabon kalmar sirri",
    133: "Tabbatar Sabuwar kalmar sirri",
    134: "Shigar da sabon kalmar sirri",
    135: "Sake",
    136: "Gyara bayanin martaba",
    137: "Sunan mai amfani",
    138: "Shigar da sunan mai amfani",
    139: "E-mail",
    140: "Shigar da imel ɗin mai amfani",
    141: "Shigar da Wayar Mai Amfani",
    142: "Canza",
    143: "Bude Gallery",
    144: "Buɗe Kamara",
    145: "Canja kalmar sirri",
    146: "Nemi karba",
    147: "Menene cikakken Sunanku",
    148: "Shigar da sunan ku",
    149: "Shigar da Adireshin ku",
    150: "32 George Str, Lekki, Jihar Legas",
    151: "Shigar da wayar mai aikawa",
    152: "+234 817 XXX XXXX",
    153: "Shiga A'a Wayar Mai karɓa",
    154: "Shigar da Rukunin Kunshin",
    155: "Shigar da Sunan Kunshin",
    156: "Tufa",
    157: "Shigar da Bayanin samfur",
    158: "Kayan ruwan hoda tare da ƙirar dutse",
    159: "Zaɓi Adireshin Karɓa",
    160: "Bayyana samfurin",
    161: "Zaɓi Adireshin Bayarwa",
    162: "Nemi",
    163: "Nemi A Karɓi",
    164: "Mai sauri",
    165: "Abin dogaro",
    166: "Mai inganci",
    167: "Sabis ɗin isar da saƙo mai sauri.",
    168: "Amintacce bayarwa don kasuwanci",
    169: "Tsarin inganci da aminci",
    170: "Barka da zuwa duniyarmu",
    171: "Za ku iya fara yin odar karba a yanzu",
    172: "Ana aiwatar da odar ku",
    173: "An karɓi odar ku kuma ana sarrafata",
    174: "Yawan abu"
  };

  //
  //
  //
  setLang(int id) {
    if (id == english) {
      defaultLang = langEng;
      init = true;
    }
    if (id == german) {
      defaultLang = langDeu;
      init = true;
    }
    if (id == espanol) {
      defaultLang = langEsp;
      init = true;
    }
    if (id == igbo) {
      defaultLang = langIgbo;
      init = true;
    }
    if (id == yor) {
      defaultLang = langYor;
      init = true;
    }
    if (id == hausa) {
      defaultLang = langHausa;
      init = true;
    }
    for (var lang in langData) {
      lang.current = false;
      if (lang.id == id) lang.current = true;
    }
  }

  late Map<int, String> defaultLang;
  var init = false;

  String? get(int id) {
    if (!init) return "";
    return defaultLang[id];
  }
}
